### PR TITLE
Update algorithms interface, update docs

### PR DESCRIPTION
**Pull request by lostella**
This PR touches lots things, but the changes are not *that* many, with several concerning documentation. However, a few breaking changes are there. All of the changes were done working backwards from the documentation process, trying to simplify and uniformize the interface to algorithms.

## Breaking changes
- All algorithms now require the initial iterate as keyword arguments (before it was positional). Therefore now all arguments are keyword arguments.
- `DavisYin` now has `f` as smooth term (was `h`) to align it with all other algorithms; the smoothness constant was renamed to `Lf` as a consequence.
- `DRLS` now uses `mf` as strong convexity parameter (was `muf`).
- `SFISTA` arguments were uniformized to other algorithms: `x0` is the initial iterate, `g` is the proximable term, `mf` is the convexity modulus of `f`.

## Other changes
- Introduced the `IterativeAlgorithm` type, which encodes at once how to construct and iterate a given iterator type, with stopping criterion and verbosity and so on; specific algorithms construct an object of this type now, with a particular iterator type, default stopping criterion (which can now be replaced with anything if one wants, not just tuned via the tolerance) and default values for other options.
- Reworked PANOC, PANOCplus, and ZeroFPR `iterate` method to make it type stable (a new state is always returned, never `nothing`).

## Documentation changes
- Reorganized and updated material.
- Fixed docstrings.
- Added docstrings for the “solver” interface to algorithms.
- Switched to Plots for doing plots, instead of Gadfly.

## Tests
Except for the changes to the algorithms interface (described above), test scripts are unchanged.

### CODE REVIEW

**Comment by lostella** [comment]
@aldma since you contributed PANOCplus, I would kindly ask you to take a look to the changes I’m doing to it here (see PR description), whenever you are able to, and confirm that they look OK.

Feel free to focus on the changes to PANOCplus, of course :-)

In particular, I’m changing the behavior when the maximum number of backtracking steps on tau is exceeded, to have the “nominal” forward-backward step accepted instead of the iteration halting.

**Comment by lostella** [comment]
@wwkong I’m proposing some breaking changes to the SFISTA method you contributed, to uniformize the naming across algorithms: the proximable term `h` becomes `g`, the initial iterate `y0` becomes `x0`, the convexity modulus of `f` becomes `mf`. So this PR is simply renaming things, and the algorithm unaffected. Please feel free to look into the changes (only the SFISTA ones!) and confirm I didn’t do anything silly there :-)

**Comment by aldma** [comment]
@lostella Your changes to PANOCplus look good. Nice refactoring and docs, indeed!

**Comment by lostella** [comment]
Merging, I’ll address further comments separately, if there are any 🙃

**Pull request merged**
